services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: remix_user
      POSTGRES_PASSWORD: remix_password
      POSTGRES_DB: remix_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: