name: Test and Deploy to Cloudflare Workers

on:
  push:
    branches:
      - main # Trigger on push to the main branch
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main # Trigger on pull requests to main
  workflow_dispatch: # Allow manual triggering from GitHub UI

jobs:
  test:
    runs-on: ubuntu-latest
    name: Run Tests
    steps:
      # Check out the repository code
      - uses: actions/checkout@v3

      # Setup Node.js environment
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      # Install dependencies
      - name: Install dependencies
        run: npm ci

      # Generate Prisma Client for testing
      - name: Generate Prisma Client
        run: npm run prisma:generate
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}

      # Run tests
      - name: Run tests
        run: npm test
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          # Copy any other environment variables you have in .dev.vars
          # For example:
          # API_KEY: ${{ secrets.API_KEY }}

  deploy:
    needs: test # This ensures deploy only runs if tests pass
    runs-on: ubuntu-latest
    name: Deploy
    # Only deploy on push to main, not on pull requests
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
      # Check out the repository code
      - uses: actions/checkout@v3

      # Setup Node.js environment for the build
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20 # Matches the engine requirement in package.json

      # Install all dependencies defined in package.json
      - name: Install dependencies
        run: npm ci

      # Generate Prisma Client with the --no-engine flag (for Cloudflare Workers compatibility)
      - name: Generate Prisma Client
        run: npm run prisma:generate
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}

      # Run the build script defined in package.json
      - name: Build
        run: npm run build
        env:
          # All environment variables needed for the build process
          DATABASE_URL: ${{ secrets.DATABASE_URL }}

      # Deploy to Cloudflare using wrangler
      - name: Deploy to Cloudflare
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }} # Authentication token for Cloudflare API
          accountId: ${{ secrets.CF_ACCOUNT_ID }} # Your Cloudflare account identifier
          command: deploy # Runs 'wrangler deploy' command
          wranglerVersion: "3.x" # Ensures compatibility with your project's wrangler version
        env:
          # Environment variables needed during deployment
          # These will be available to your application at runtime
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          # Add any other environment variables you use in your application
