name: Run Tests

on:
  push:
    branches:
      - "*" # Run on pushes to any branch
  pull_request:
    branches:
      - "*" # Run on PRs to any branch

jobs:
  test:
    runs-on: ubuntu-latest
    name: Test
    steps:
      # Check out the repository code
      - uses: actions/checkout@v3

      # Setup Node.js environment
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      # Install all dependencies defined in package.json
      - name: Install dependencies
        run: npm ci

      # Generate Prisma Client with the --no-engine flag
      - name: Generate Prisma Client
        run: npx prisma generate --no-engine
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}

      # Run tests (update this command to match your test script in package.json)
      - name: Run tests
        run: npm test
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          # Add any other environment variables needed for tests
