name: Run Tests

on:
  push:
    branches:
      - "*" # Run on pushes to any branch
  pull_request:
    branches:
      - "*" # Run on PRs to any branch

jobs:
  test:
    runs-on: ubuntu-latest
    name: Test
    steps:
      # Check out the repository code
      - uses: actions/checkout@v3

      # Setup Node.js environment
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      # Install all dependencies defined in package.json
      - name: Install dependencies
        run: npm ci

      # Install Playwright browsers
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      # Generate Prisma Client with the --no-engine flag
      - name: Generate Prisma Client
        run: npx prisma generate --no-engine
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}

      # Run unit tests
      - name: Run unit tests
        run: npm test
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}

      # Start the app server in the background
      - name: Start app server
        run: npm run dev &
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}

      # Wait for the app to be ready
      - name: Wait for app server
        run: npx wait-on http://localhost:5173

      # Run E2E tests
      - name: Run E2E tests
        run: npm run test:e2e
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          BASE_URL: http://localhost:5173

      # Upload test results
      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
